vich_uploader:
    db_driver: orm

    mappings:
       bottle:
           uri_prefix: /images/bottle
           upload_destination: '%kernel.project_dir%/public/images/bottle'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
